
services:
  frontend:
    build: ./frontEnd
    ports:
      - 8081:8081
  backend:
    build: ./backEnd
    ports:
      - 8080:8080
    environment:
      - DB_URL=postgres://database/events
  database:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - events:/var/lib/postgresql/data

volumes:
  events:
