
services:
  frontend:
    build: ./frontEnd
    ports:
      - 8081:8081
  backend:
    build: ./backEnd
    ports:
      - 8080:8080
        #environment:
      #DB_HOST: database
        #DB_PORT: 5432
        #DB_USER: root
        #DB_PASSWORD: 1234
        #DB_NAME: events
        #depends_on:
      #- database

        #  database:
        #image: postgres
        #ports:
        #- 5432:5432
        #volumes:
        #- events:/var/lib/postgresql/data
        #environment:
        #POSTGRES_USER: root
        #POSTGRES_PASSWORD: 1234
        #POSTGRES_DB: events

        #volumes:
        #events:
